import type { JSONSchema } from 'json-schema-to-ts';
import * as primitives from './transport.js';
import * as entities from './entities.js';
import * as ownership from './ownership.js';
import * as reads from './reads.js';
import * as sync from './sync.js';
import * as lifecycle from './lifecycle.js';
import { apiErrorSchema, liveResponseSchema } from './http.js';
import { backupSchema } from './backup.js';
import { commandEnvelopeSchema } from './commands.js';
import { objectSchema } from './schema.js';

export const contractSchemas = {
  NonnegativeMoney: primitives.nonnegativeMoneySchema,
  PositiveMoney: primitives.positiveMoneySchema,
  Quantity: primitives.quantitySchema,
  Stock: primitives.stockSchema,
  NonnegativeStock: primitives.nonnegativeStockSchema,
  Cursor: primitives.cursorSchema,
  ProtocolVersion: primitives.protocolVersionSchema,
  DomainVersion: primitives.domainVersionSchema,
  Money: primitives.moneySchema,
  Percentage: primitives.percentageSchema,
  Revision: primitives.revisionSchema,
  Timestamp: primitives.timestampSchema,
  UUID: primitives.uuidSchema,
  UUIDv7: primitives.uuidV7Schema,
  ApiError: apiErrorSchema,
  Live: liveResponseSchema,
  Health: objectSchema({ status: { type: 'string', const: 'ok' } }),
  NoQuery: ownership.noQuerySchema,
  InventoryParams: ownership.inventoryParamsSchema,
  OperationParams: ownership.operationParamsSchema,
  ProductParams: ownership.productParamsSchema,
  SaleParams: ownership.saleParamsSchema,
  PurchaseParams: ownership.purchaseParamsSchema,
  Inventory: ownership.inventoryMetadataSchema,
  Business: ownership.businessSchema,
  Me: ownership.meResponseSchema,
  BootstrapRequest: ownership.bootstrapRequestSchema,
  BootstrapResponse: ownership.bootstrapResponseSchema,
  Csrf: ownership.csrfResponseSchema,
  Product: entities.productSchema,
  InventoryState: entities.inventoryStateSchema,
  ProductRead: entities.productReadSchema,
  Sale: entities.saleSchema,
  SaleItem: entities.saleItemSchema,
  SaleDetailItem: entities.saleDetailItemSchema,
  Purchase: entities.purchaseSchema,
  StockAdjustment: entities.adjustmentSchema,
  InventoryMovement: entities.movementSchema,
  CreateProductResult: entities.createProductResultSchema,
  ProductMutationResult: entities.productMutationResultSchema,
  RegisterSaleResult: entities.registerSaleResultSchema,
  RegisterPurchaseResult: entities.registerPurchaseResultSchema,
  AdjustStockResult: entities.adjustStockResultSchema,
  VoidSaleResult: entities.voidSaleResultSchema,
  VoidPurchaseResult: entities.voidPurchaseResultSchema,
  SaleDetail: entities.saleDetailSchema,
  PurchaseDetail: entities.purchaseDetailSchema,
  ProductPage: reads.productPageSchema,
  HistoryEntry: reads.historyEntrySchema,
  HistoryPage: reads.historyPageSchema,
  Dashboard: reads.dashboardSchema,
  PaginationQuery: reads.paginationQuerySchema,
  ProductQuery: reads.productQuerySchema,
  HistoryQuery: reads.historyQuerySchema,
  BarcodeQuery: reads.barcodeQuerySchema,
  CommandEnvelope: commandEnvelopeSchema,
  CreateProductCommand: commandEnvelopeSchema.oneOf[0],
  UpdateProductCommand: commandEnvelopeSchema.oneOf[1],
  ArchiveProductCommand: commandEnvelopeSchema.oneOf[2],
  RegisterSaleCommand: commandEnvelopeSchema.oneOf[3],
  RegisterPurchaseCommand: commandEnvelopeSchema.oneOf[4],
  AdjustStockCommand: commandEnvelopeSchema.oneOf[5],
  VoidSaleCommand: commandEnvelopeSchema.oneOf[6],
  VoidPurchaseCommand: commandEnvelopeSchema.oneOf[7],
  DeviceRegistration: sync.deviceRegistrationSchema,
  DeviceRegistrationResult: sync.deviceRegistrationResultSchema,
  PushRequest: sync.pushRequestSchema,
  PushResponse: sync.pushResponseSchema,
  PushCommandResult: sync.pushCommandResultSchema,
  ChangeSet: sync.changeSetSchema,
  ChangesQuery: sync.changesQuerySchema,
  ChangesResponse: sync.changesResponseSchema,
  SnapshotRequest: sync.snapshotRequestSchema,
  SnapshotDescriptor: sync.snapshotDescriptorSchema,
  SnapshotPageQuery: sync.snapshotPageQuerySchema,
  SnapshotPage: sync.snapshotPageSchema,
  OperationReceipt: sync.operationReceiptSchema,
  BackupV1: backupSchema,
  ImportReservation: lifecycle.importReservationSchema,
  ImportChunk: lifecycle.importChunkSchema,
  ImportProgress: lifecycle.importProgressSchema,
  ImportCommit: lifecycle.importCommitSchema,
  ImportCommitResult: lifecycle.importCommitResultSchema,
  ImportCancelResult: lifecycle.importCancelResultSchema,
  AccountExport: lifecycle.accountExportSchema,
  AccountDeletionRequest: lifecycle.accountDeletionRequestSchema,
  AccountDeletionResult: lifecycle.accountDeletionResultSchema,
} as const satisfies Readonly<Record<string, JSONSchema>>;

export type ContractSchemaName = keyof typeof contractSchemas;
export type AuthLevel =
  | 'public'
  | 'verified-session'
  | 'cloud-inventory'
  | 'verified-cloud-owner'
  | 'import-owner'
  | 'recent-session'
  | 'recent-cloud-inventory';
export interface RouteContract {
  readonly method: 'get' | 'post' | 'patch' | 'put' | 'delete';
  readonly path: string;
  readonly operationId: string;
  readonly summary: string;
  readonly auth: AuthLevel;
  readonly implementationStatus: 'implemented' | 'planned';
  readonly params?:
    | 'InventoryParams'
    | 'OperationParams'
    | 'ProductParams'
    | 'SaleParams'
    | 'PurchaseParams';
  readonly query?: ContractSchemaName;
  readonly body?: ContractSchemaName;
  readonly responses: Readonly<Record<number, ContractSchemaName>>;
  readonly command?: boolean;
  readonly idempotency?: boolean;
}

const inventoryPath = '/v1/inventories/{inventoryId}';
const readErrors = {
  400: 'ApiError',
  401: 'ApiError',
  403: 'ApiError',
  404: 'ApiError',
  429: 'ApiError',
  500: 'ApiError',
} as const;
const mutationErrors = {
  ...readErrors,
  409: 'ApiError',
  413: 'ApiError',
  415: 'ApiError',
  422: 'ApiError',
  503: 'ApiError',
} as const;
function planned(
  method: RouteContract['method'],
  path: string,
  operationId: string,
  summary: string,
  auth: AuthLevel,
  response: ContractSchemaName,
  options: Pick<
    RouteContract,
    'query' | 'body' | 'command' | 'idempotency'
  > = {},
): RouteContract {
  return {
    method,
    path,
    operationId,
    summary,
    auth,
    implementationStatus: 'planned',
    responses: {
      ...(method === 'get' ? readErrors : mutationErrors),
      200: response,
    },
    ...options,
  };
}
export const routeContracts: readonly RouteContract[] = [
  {
    method: 'get',
    path: '/live',
    operationId: 'getLive',
    summary: 'Process liveness, without database access',
    auth: 'public',
    implementationStatus: 'implemented',
    responses: { 200: 'Live', 500: 'ApiError' },
  },
  {
    method: 'get',
    path: '/v1/session/csrf',
    operationId: 'getSessionCsrf',
    summary: 'Get a CSRF token bound to the verified session',
    auth: 'verified-session',
    implementationStatus: 'implemented',
    query: 'NoQuery',
    responses: { ...readErrors, 200: 'Csrf' },
  },
  {
    method: 'get',
    path: '/v1/me',
    operationId: 'getMe',
    summary: 'Own identity, access and supported versions',
    auth: 'verified-session',
    implementationStatus: 'implemented',
    query: 'NoQuery',
    responses: { ...readErrors, 200: 'Me' },
  },
  {
    method: 'post',
    path: '/v1/business',
    operationId: 'bootstrapBusiness',
    summary: 'Bootstrap an empty own inventory; matching retry returns 200',
    auth: 'verified-session',
    implementationStatus: 'implemented',
    query: 'NoQuery',
    body: 'BootstrapRequest',
    responses: {
      ...mutationErrors,
      200: 'BootstrapResponse',
      201: 'BootstrapResponse',
    },
  },
  {
    method: 'get',
    path: inventoryPath,
    operationId: 'getInventory',
    summary: 'Own cloud inventory metadata',
    auth: 'cloud-inventory',
    implementationStatus: 'implemented',
    params: 'InventoryParams',
    query: 'NoQuery',
    responses: { ...readErrors, 200: 'Inventory' },
  },
  planned(
    'get',
    '/health',
    'getHealth',
    'Database readiness; currently returns 404',
    'public',
    'Health',
  ),
  {
    ...planned(
      'get',
      `${inventoryPath}/dashboard`,
      'getDashboard',
      'Business-day summary, low stock, top sellers and recent operations',
      'cloud-inventory',
      'Dashboard',
    ),
    params: 'InventoryParams',
    implementationStatus: 'implemented',
    query: 'NoQuery',
  },
  {
    ...planned(
      'get',
      `${inventoryPath}/products`,
      'listProducts',
      'Active products ordered by createdAt DESC, id DESC',
      'cloud-inventory',
      'ProductPage',
      { query: 'ProductQuery' },
    ),
    params: 'InventoryParams',
    implementationStatus: 'implemented',
  },
  {
    ...planned(
      'get',
      `${inventoryPath}/products/by-barcode`,
      'getProductByBarcode',
      'Exact active barcode lookup',
      'cloud-inventory',
      'ProductRead',
      { query: 'BarcodeQuery' },
    ),
    params: 'InventoryParams',
    implementationStatus: 'implemented',
  },
  {
    ...planned(
      'get',
      `${inventoryPath}/products/{productId}`,
      'getProduct',
      'Product, current state and profitability',
      'cloud-inventory',
      'ProductRead',
    ),
    params: 'ProductParams',
    implementationStatus: 'implemented',
    query: 'NoQuery',
  },
  {
    ...planned(
      'post',
      `${inventoryPath}/products`,
      'createProduct',
      'Create a product and optional initial stock movement',
      'cloud-inventory',
      'CreateProductResult',
      { body: 'CreateProductCommand', command: true },
    ),
    implementationStatus: 'implemented',
    params: 'InventoryParams',
  },
  {
    ...planned(
      'patch',
      `${inventoryPath}/products/{productId}`,
      'updateProduct',
      'Update metadata with expected metadata revision',
      'cloud-inventory',
      'ProductMutationResult',
      { body: 'UpdateProductCommand', command: true },
    ),
    implementationStatus: 'implemented',
    params: 'ProductParams',
  },
  {
    ...planned(
      'post',
      `${inventoryPath}/products/{productId}/archive`,
      'archiveProduct',
      'Archive a product; no financial tombstone',
      'cloud-inventory',
      'ProductMutationResult',
      { body: 'ArchiveProductCommand', command: true },
    ),
    implementationStatus: 'implemented',
    params: 'ProductParams',
  },
  {
    ...planned(
      'get',
      `${inventoryPath}/stock-low`,
      'listLowStock',
      'Active low-stock products',
      'cloud-inventory',
      'ProductPage',
      { query: 'PaginationQuery' },
    ),
    params: 'InventoryParams',
    implementationStatus: 'implemented',
  },
  {
    ...planned(
      'post',
      `${inventoryPath}/sales`,
      'registerSale',
      'Atomically register all sale lines; negative stock remains allowed',
      'cloud-inventory',
      'RegisterSaleResult',
      { body: 'RegisterSaleCommand', command: true },
    ),
    implementationStatus: 'implemented',
    params: 'InventoryParams',
  },
  {
    ...planned(
      'get',
      `${inventoryPath}/sales/{saleId}`,
      'getSale',
      'Historical snapshots and void eligibility',
      'cloud-inventory',
      'SaleDetail',
    ),
    params: 'SaleParams',
    implementationStatus: 'implemented',
    query: 'NoQuery',
  },
  {
    ...planned(
      'post',
      `${inventoryPath}/sales/{saleId}/void`,
      'voidSale',
      'Void eligible sale; same operation replays, distinct stale void conflicts',
      'cloud-inventory',
      'VoidSaleResult',
      { body: 'VoidSaleCommand', command: true },
    ),
    params: 'SaleParams',
    implementationStatus: 'implemented',
  },
  {
    ...planned(
      'post',
      `${inventoryPath}/purchases`,
      'registerPurchase',
      'Register a single-product purchase and derived costs',
      'cloud-inventory',
      'RegisterPurchaseResult',
      { body: 'RegisterPurchaseCommand', command: true },
    ),
    implementationStatus: 'implemented',
    params: 'InventoryParams',
  },
  {
    ...planned(
      'get',
      `${inventoryPath}/purchases/{purchaseId}`,
      'getPurchase',
      'Purchase snapshots and void eligibility',
      'cloud-inventory',
      'PurchaseDetail',
    ),
    params: 'PurchaseParams',
    implementationStatus: 'implemented',
    query: 'NoQuery',
  },
  {
    ...planned(
      'post',
      `${inventoryPath}/purchases/{purchaseId}/void`,
      'voidPurchase',
      'Void eligible purchase; restore prior average, same operation replays, distinct stale void conflicts',
      'cloud-inventory',
      'VoidPurchaseResult',
      { body: 'VoidPurchaseCommand', command: true },
    ),
    params: 'PurchaseParams',
    implementationStatus: 'implemented',
  },
  {
    ...planned(
      'post',
      `${inventoryPath}/adjustments`,
      'adjustStock',
      'Record actual stock with accepted cost; server derives difference',
      'cloud-inventory',
      'AdjustStockResult',
      { body: 'AdjustStockCommand', command: true },
    ),
    params: 'InventoryParams',
    implementationStatus: 'implemented',
  },
  {
    ...planned(
      'get',
      `${inventoryPath}/history`,
      'listHistory',
      'Commercial history ordered by effectiveAt DESC, createdAt DESC, id DESC',
      'cloud-inventory',
      'HistoryPage',
      { query: 'HistoryQuery' },
    ),
    params: 'InventoryParams',
    implementationStatus: 'implemented',
  },
  {
    method: 'get',
    path: `${inventoryPath}/operations/{operationId}`,
    operationId: 'getOperation',
    summary: 'Own durable command receipt',
    auth: 'cloud-inventory',
    implementationStatus: 'implemented',
    params: 'OperationParams',
    query: 'NoQuery',
    responses: { ...readErrors, 200: 'OperationReceipt' },
  },
  planned(
    'post',
    `${inventoryPath}/sync/devices`,
    'registerDevice',
    'Register an installation, without hardware identifiers',
    'cloud-inventory',
    'DeviceRegistrationResult',
    { body: 'DeviceRegistration' },
  ),
  planned(
    'post',
    `${inventoryPath}/sync/push`,
    'pushCommands',
    'FIFO batch, max 50 commands / 1 MiB, one transaction per command',
    'cloud-inventory',
    'PushResponse',
    { body: 'PushRequest' },
  ),
  {
    ...planned(
      'get',
      `${inventoryPath}/sync/changes`,
      'pullChanges',
      'Complete changesets; stable high-water mark and generation-scoped cursor',
      'cloud-inventory',
      'ChangesResponse',
      { query: 'ChangesQuery' },
    ),
    responses: { ...readErrors, 200: 'ChangesResponse', 410: 'ApiError' },
  },
  planned(
    'post',
    `${inventoryPath}/sync/snapshots`,
    'createSnapshot',
    'Create a consistent snapshot expiring in 24 hours',
    'cloud-inventory',
    'SnapshotDescriptor',
    { body: 'SnapshotRequest', idempotency: true },
  ),
  {
    ...planned(
      'get',
      `${inventoryPath}/sync/snapshots/{snapshotId}`,
      'readSnapshot',
      'Read a consistent snapshot page',
      'cloud-inventory',
      'SnapshotPage',
      { query: 'SnapshotPageQuery' },
    ),
    responses: { ...readErrors, 200: 'SnapshotPage', 410: 'ApiError' },
  },
  planned(
    'post',
    '/v1/imports',
    'reserveImport',
    'Reserve an initial backup V1 import into an empty cloud dataset',
    'verified-cloud-owner',
    'ImportProgress',
    { body: 'ImportReservation', idempotency: true },
  ),
  planned(
    'put',
    '/v1/imports/{importId}/chunks/{index}',
    'uploadImportChunk',
    'Upload UTF-8 JSON fragment with index and SHA-256',
    'import-owner',
    'ImportProgress',
    { body: 'ImportChunk' },
  ),
  planned(
    'get',
    '/v1/imports/{importId}',
    'getImportProgress',
    'Read own staged import progress',
    'import-owner',
    'ImportProgress',
  ),
  planned(
    'post',
    '/v1/imports/{importId}/commit',
    'commitImport',
    'Activate a validated dataset atomically',
    'import-owner',
    'ImportCommitResult',
    { body: 'ImportCommit', idempotency: true },
  ),
  planned(
    'delete',
    '/v1/imports/{importId}',
    'cancelImport',
    'Cancel staging without deleting active data',
    'import-owner',
    'ImportCancelResult',
  ),
  {
    method: 'get',
    path: `${inventoryPath}/backup`,
    operationId: 'downloadBackup',
    summary: 'Consistent backup V1; existing numeric scaled-unit format',
    auth: 'recent-cloud-inventory',
    implementationStatus: 'implemented',
    params: 'InventoryParams',
    query: 'NoQuery',
    responses: { ...readErrors, 200: 'BackupV1' },
  },
  {
    method: 'get',
    path: '/v1/me/export',
    operationId: 'exportAccount',
    summary:
      'Export own profile and consistent dataset with recent authentication',
    auth: 'recent-session',
    implementationStatus: 'implemented',
    query: 'NoQuery',
    responses: { ...readErrors, 200: 'AccountExport' },
  },
  {
    ...planned(
      'post',
      '/v1/me/deletion',
      'requestAccountDeletion',
      'Request durable account/cloud deletion and revoke sessions',
      'recent-session',
      'AccountDeletionResult',
      { body: 'AccountDeletionRequest', idempotency: true },
    ),
    responses: { ...mutationErrors, 202: 'AccountDeletionResult' },
  },
];
